safe:        false
port:        4000

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   /:year/:month/:title

title:       Laurel Goodhart's Resume
description: Resume
base:        https://konahart.com/resume
author:      Laurel Kona Goodhart
email:       hi@konahart.com

exclude:     [drafts, _site, scripts]
